// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardflipController from "./cardflip_controller"
application.register("cardflip", CardflipController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NewlotController from "./newlot_controller"
application.register("newlot", NewlotController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
