// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvoiceController from "./invoice_controller"
application.register("invoice", InvoiceController)

import NewinvoiceController from "./newinvoice_controller"
application.register("newinvoice", NewinvoiceController)

import NewlotController from "./newlot_controller"
application.register("newlot", NewlotController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
